# site settings
title: qwqcxh
description: Notes on Computer Architecture, Linux Kernel and LLVM Compiler.

# social
social:
  email: qwqcxh@gmail.com
  github: https://github.com/qaqcxh
# Build settings
# theme: minima

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

url: https://qaqcxh.github.io/Blogs/
baseurl: "/Blogs"

permalink: /:categories/:title:output_ext

# default values
defaults:
  -
    values:
      layout: "markdown"

# plugins
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
